import type { Product } from "./database.types";

// Demo data from actual Ragic export (subset)
// Using 'as Product[]' since demo data omits fields that have DB defaults
export const DEMO_PRODUCTS = [
  {
    id: 1, product_name: "矽藻土杯墊", sku: "YW-矽藻土杯墊00001-圓形-大理石紋",
    category: "收納好物", variant_name: "圓形-大理石紋", selection_number: "00001",
    shopee_spec_id: null, order_link: null, product_positioning: "利潤款",
    product_image: null, notes: null, selling_price: 99, purchase_price_cny: 3.5,
    product_status: "穩定銷售", unit_cost_ntd: 25.8, platform_fee_rate: 0.145,
    weight_kg: 0.15, safety_stock: 20, total_purchased_qty: 200,
    total_sold_qty: 156, total_shipped_qty: 156, stock_qty: 44,
    avg_daily_sales: 1.2, created_at: "", updated_at: "",
    domestic_shipping_thrown: null, domestic_shipping_per_unit_cny: null,
    initial_order_qty: null, domestic_shipping_per_unit_thrown: null,
    avg_shipping_days: null, unit_profit: null, total_purchase_cost: 0,
    avg_purchase_price: null, current_stock_cost: 0, total_sales_revenue: 0,
    gross_margin: 0.63, realized_profit: 0, shopee_fee_total: 0,
    net_revenue_subtotal: 0, first_order_date: null, total_order_days: null,
    latest_po_number: null,
  },
  {
    id: 2, product_name: "實木三層收納置物架", sku: "YW-實木三層架00045-原木色",
    category: "收納好物", variant_name: "原木色", selection_number: "00045",
    shopee_spec_id: null, order_link: null, product_positioning: "利潤款",
    product_image: null, notes: null, selling_price: 599, purchase_price_cny: 45,
    product_status: "穩定銷售", unit_cost_ntd: 280, platform_fee_rate: 0.145,
    weight_kg: 2.5, safety_stock: 10, total_purchased_qty: 60,
    total_sold_qty: 48, total_shipped_qty: 48, stock_qty: 12,
    avg_daily_sales: 0.4, created_at: "", updated_at: "",
    domestic_shipping_thrown: null, domestic_shipping_per_unit_cny: null,
    initial_order_qty: null, domestic_shipping_per_unit_thrown: null,
    avg_shipping_days: null, unit_profit: null, total_purchase_cost: 0,
    avg_purchase_price: null, current_stock_cost: 0, total_sales_revenue: 0,
    gross_margin: 0.46, realized_profit: 0, shopee_fee_total: 0,
    net_revenue_subtotal: 0, first_order_date: null, total_order_days: null,
    latest_po_number: null,
  },
  {
    id: 3, product_name: "分裝瓶", sku: "YW-分裝瓶00023-100ml透明",
    category: "浴廁區", variant_name: "100ml透明", selection_number: "00023",
    shopee_spec_id: null, order_link: null, product_positioning: "引流款",
    product_image: null, notes: null, selling_price: 39, purchase_price_cny: 1.2,
    product_status: "穩定銷售", unit_cost_ntd: 12.5, platform_fee_rate: 0.145,
    weight_kg: 0.05, safety_stock: 50, total_purchased_qty: 300,
    total_sold_qty: 268, total_shipped_qty: 268, stock_qty: 32,
    avg_daily_sales: 2.1, created_at: "", updated_at: "",
    domestic_shipping_thrown: null, domestic_shipping_per_unit_cny: null,
    initial_order_qty: null, domestic_shipping_per_unit_thrown: null,
    avg_shipping_days: null, unit_profit: null, total_purchase_cost: 0,
    avg_purchase_price: null, current_stock_cost: 0, total_sales_revenue: 0,
    gross_margin: 0.56, realized_profit: 0, shopee_fee_total: 0,
    net_revenue_subtotal: 0, first_order_date: null, total_order_days: null,
    latest_po_number: null,
  },
  {
    id: 4, product_name: "百摺衛生紙套", sku: "YW-百摺衛生紙套00067-米白",
    category: "浴廁區", variant_name: "米白", selection_number: "00067",
    shopee_spec_id: null, order_link: null, product_positioning: "一般款",
    product_image: null, notes: null, selling_price: 159, purchase_price_cny: 12,
    product_status: "穩定銷售", unit_cost_ntd: 78, platform_fee_rate: 0.145,
    weight_kg: 0.3, safety_stock: 15, total_purchased_qty: 80,
    total_sold_qty: 63, total_shipped_qty: 63, stock_qty: 17,
    avg_daily_sales: 0.5, created_at: "", updated_at: "",
    domestic_shipping_thrown: null, domestic_shipping_per_unit_cny: null,
    initial_order_qty: null, domestic_shipping_per_unit_thrown: null,
    avg_shipping_days: null, unit_profit: null, total_purchase_cost: 0,
    avg_purchase_price: null, current_stock_cost: 0, total_sales_revenue: 0,
    gross_margin: 0.38, realized_profit: 0, shopee_fee_total: 0,
    net_revenue_subtotal: 0, first_order_date: null, total_order_days: null,
    latest_po_number: null,
  },
  {
    id: 5, product_name: "金屬擠護手霜", sku: "YW-金屬擠護手霜00078-愛心短款",
    category: "收納好物", variant_name: "愛心護手霜擠壓器（短款）", selection_number: "00078",
    shopee_spec_id: null, order_link: null, product_positioning: "引流款",
    product_image: null, notes: null, selling_price: 35, purchase_price_cny: 3.41,
    product_status: "測品", unit_cost_ntd: 17.82, platform_fee_rate: 0.145,
    weight_kg: 0.013, safety_stock: 5, total_purchased_qty: 5,
    total_sold_qty: 0, total_shipped_qty: 0, stock_qty: 5,
    avg_daily_sales: 0, created_at: "", updated_at: "",
    domestic_shipping_thrown: null, domestic_shipping_per_unit_cny: null,
    initial_order_qty: null, domestic_shipping_per_unit_thrown: null,
    avg_shipping_days: null, unit_profit: null, total_purchase_cost: 0,
    avg_purchase_price: null, current_stock_cost: 0, total_sales_revenue: 0,
    gross_margin: 0.35, realized_profit: 0, shopee_fee_total: 0,
    net_revenue_subtotal: 0, first_order_date: null, total_order_days: null,
    latest_po_number: null,
  },
  {
    id: 6, product_name: "高密度海綿菜瓜布", sku: "YW-高密度海綿菜瓜布00100-5入",
    category: "餐廚區", variant_name: "混色 5入裝", selection_number: "00100",
    shopee_spec_id: null, order_link: null, product_positioning: "一般款",
    product_image: null, notes: null, selling_price: 50, purchase_price_cny: 4.03,
    product_status: "測品", unit_cost_ntd: 18.36, platform_fee_rate: 0.145,
    weight_kg: 0.1, safety_stock: 10, total_purchased_qty: 10,
    total_sold_qty: 0, total_shipped_qty: 0, stock_qty: 10,
    avg_daily_sales: 0, created_at: "", updated_at: "",
    domestic_shipping_thrown: null, domestic_shipping_per_unit_cny: null,
    initial_order_qty: null, domestic_shipping_per_unit_thrown: null,
    avg_shipping_days: null, unit_profit: null, total_purchase_cost: 0,
    avg_purchase_price: null, current_stock_cost: 0, total_sales_revenue: 0,
    gross_margin: 0.49, realized_profit: 0, shopee_fee_total: 0,
    net_revenue_subtotal: 0, first_order_date: null, total_order_days: null,
    latest_po_number: null,
  },
  {
    id: 7, product_name: "矽藻土杯墊", sku: "YW-矽藻土杯墊00001-方形-素色白",
    category: "收納好物", variant_name: "方形-素色白", selection_number: "00001",
    shopee_spec_id: null, order_link: null, product_positioning: "利潤款",
    product_image: null, notes: null, selling_price: 89, purchase_price_cny: 3.2,
    product_status: "穩定銷售", unit_cost_ntd: 24.5, platform_fee_rate: 0.145,
    weight_kg: 0.14, safety_stock: 20, total_purchased_qty: 180,
    total_sold_qty: 175, total_shipped_qty: 175, stock_qty: 5,
    avg_daily_sales: 1.0, created_at: "", updated_at: "",
    domestic_shipping_thrown: null, domestic_shipping_per_unit_cny: null,
    initial_order_qty: null, domestic_shipping_per_unit_thrown: null,
    avg_shipping_days: null, unit_profit: null, total_purchase_cost: 0,
    avg_purchase_price: null, current_stock_cost: 0, total_sales_revenue: 0,
    gross_margin: 0.60, realized_profit: 0, shopee_fee_total: 0,
    net_revenue_subtotal: 0, first_order_date: null, total_order_days: null,
    latest_po_number: null,
  },
  {
    id: 8, product_name: "壁掛式置物架", sku: "YW-壁掛式置物架00052-白色",
    category: "浴廁區", variant_name: "白色", selection_number: "00052",
    shopee_spec_id: null, order_link: null, product_positioning: "一般款",
    product_image: null, notes: null, selling_price: 199, purchase_price_cny: 18,
    product_status: "穩定銷售", unit_cost_ntd: 110, platform_fee_rate: 0.145,
    weight_kg: 0.5, safety_stock: 8, total_purchased_qty: 40,
    total_sold_qty: 40, total_shipped_qty: 40, stock_qty: 0,
    avg_daily_sales: 0.3, created_at: "", updated_at: "",
    domestic_shipping_thrown: null, domestic_shipping_per_unit_cny: null,
    initial_order_qty: null, domestic_shipping_per_unit_thrown: null,
    avg_shipping_days: null, unit_profit: null, total_purchase_cost: 0,
    avg_purchase_price: null, current_stock_cost: 0, total_sales_revenue: 0,
    gross_margin: 0.31, realized_profit: 0, shopee_fee_total: 0,
    net_revenue_subtotal: 0, first_order_date: null, total_order_days: null,
    latest_po_number: null,
  },
] as Product[];
